title: benji bee
author: "Benji Bilheimer"
description: "...a freelance photographer most recently based in Montr&eacute;al, Qu&eacute;bec specializing in journalistic, reportage-style photography projects around the world."

analytics: UA-31898685-1

pygments: false
permalink: /blog/:categories/:title
exclude: [13-7-16-backup.zip]

flickr:
  enabled:         yes
  cache_dir:       ./_cache/flickr
  shared_secret:   44a70c2a85d6d12e
  api_key:         d90bdb7483138f04b01ffa48de331334
  auth_token:      72157634461860929-a81fbb979f2cdf10